name: flutter_core_kit
description: A set of useful tools, classes, mixins & extensions used for flutter projects
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.4.0

dev_dependencies:
  very_good_analysis: ^6.0.0
