name: flutter_core_kit
description: A set of useful tools, classes, mixins & extensions used for flutter projects
version: 0.1.3
publish_to: none

environment:
  sdk: ^3.4.0

dependencies:
  meta: ^1.16.0
  rxdart: ^0.28.0
  talker: ^4.4.1

dev_dependencies:
  very_good_analysis: ^6.0.0
