name: flutter_core_kit
description: A set of useful tools, classes, mixins & extensions used for flutter projects
version: 0.1.2
publish_to: none

environment:
  sdk: ^3.4.0

dependencies:
  logger: ^2.3.0

dev_dependencies:
  very_good_analysis: ^6.0.0
